### ISSUE TITLE
Error, some dependencies are missing

### ISSUE THREAD

**Issue by Superkooka** [thenameless314159/Astron.Unpacker#1]
I have an error when I launch the Unpacker, I think some dependencies are missing (lib dir ?) so may I have to download it somewhere ? 
![image](https://user-images.githubusercontent.com/35631093/71012787-ec2f0b00-20ef-11ea-978a-99bf5544d284.png)

**Comment by BoraxKid** [comment]
Getting the same error

**Comment by thenameless314159** [comment]
I don't see this dep in any .csproj so I can't help you. Anyway this 2 years old library is not maintained nor supported anymore I invite you to update it yourself If you feels like doing it
